// <auto-generated />
namespace AuctionDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DBv4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBv4));
        
        string IMigrationMetadata.Id
        {
            get { return "202003151203506_DBv4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
